name: Md Rayhanul Islam
url: https://rayhanul.github.io
description: “Tell me and I forget. Teach me and I remember. Involve me and I learn.” Benjamin Franklin

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
